# Generated by Django 5.2 on 2025-05-21 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=50)),
                ('jornada', models.CharField(choices=[('man', 'Mañana'), ('tar', 'Tarde'), ('noc', 'Noche'), ('sab', 'Sabatino')], default='man', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_iden', models.CharField(choices=[('ti', 'Tarjeta de Identidad'), ('ci', 'Cédula de Identidad'), ('ce', 'Cédula de Extrajería'), ('ppt', 'Permiso por Protección Temporal')], default='ti', max_length=3)),
                ('num_iden', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('docen', 'Docente'), ('estud', 'Estudiante')], default='estud', max_length=5)),
                ('foto', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('act', 'Activo'), ('ina', 'Inactivo'), ('rev', 'En Revisión')], default='act', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('rec', 'Rector'), ('dir', 'Director'), ('adm', 'Administrador')], default='adm', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.curso')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ManyToManyField(related_name='docente_curso', to='usuarios.curso')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_materia', models.ManyToManyField(related_name='docente_materia', to='usuarios.materia')),
            ],
        ),
    ]
