# Generated by Django 5.2 on 2025-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='id_cargo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_jornada',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_tipo_iden',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
        migrations.AddField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(choices=[('rec', 'Rector'), ('dir', 'Director'), ('adm', 'Administrador')], default='adm', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='jornada',
            field=models.CharField(choices=[('man', 'Mañana'), ('tar', 'Tarde'), ('noc', 'Noche'), ('sab', 'Sabatino')], default='man', max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_iden',
            field=models.CharField(choices=[('ti', 'Tarjeta de Identidad'), ('ci', 'Cédula de Identidad'), ('ce', 'Cédula de Extrajería'), ('ppt', 'Permiso por Protección Temporal')], default='ti', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('act', 'Activo'), ('ina', 'Inactivo'), ('rev', 'En Revisión')], default='act', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('docen', 'Docente'), ('estud', 'Estudiante')], default='estud', max_length=5),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Jornada',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='TipoIden',
        ),
    ]
