# Generated by Django 5.2 on 2025-05-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docente',
            name='id_curso',
            field=models.ManyToManyField(db_column='id_curso', related_name='docente_curso', to='usuarios.curso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='id_materia',
            field=models.ManyToManyField(db_column='id_materia', related_name='docente_materia', to='usuarios.materia'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_persona',
            field=models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
    ]
