# Generated by Django 5.2 on 2025-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(choices=[('rec', 'Rector'), ('dir', 'Director'), ('cor', 'Coordinador'), ('adm', 'Administrador')], default='adm', max_length=3),
        ),
    ]
