# Generated by Django 5.2 on 2025-05-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenInfo',
            fields=[
                ('id_gen_info', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('csv', '.csv'), ('pdf', '.pdf'), ('word', '.docx')], default='pdf', max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaChequeo',
            fields=[
                ('id_lista_chequeo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
