# Generated by Django 5.2 on 2025-05-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faltas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaChequeo',
            fields=[
                ('id_lista_chequeo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
                ('id_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('id_falta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faltas.falta')),
            ],
        ),
        migrations.CreateModel(
            name='GenInfo',
            fields=[
                ('id_gen_info', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
                ('id_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('id_lista_chequeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_infos.listachequeo')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gen_infos.tipo')),
            ],
        ),
    ]
