# Generated by Django 5.2 on 2025-05-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0002_remove_falta_id_tipo_falta_falta_tipo_falta_and_more'),
        ('gen_infos', '0001_initial'),
        ('usuarios', '0002_remove_administrador_id_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geninfo',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='geninfo',
            name='tipo',
            field=models.CharField(choices=[('csv', '.csv'), ('pdf', '.pdf'), ('word', '.docx')], default='pdf', max_length=4),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='id_administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='id_docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='id_lista_chequeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gen_infos.listachequeo'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estudiante'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_falta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faltas.falta'),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
