# Generated by Django 5.2 on 2025-05-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0003_alter_falta_id_administrador_alter_falta_id_docente_and_more'),
        ('gen_infos', '0002_initial'),
        ('usuarios', '0002_alter_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geninfo',
            name='id_administrador',
            field=models.ForeignKey(blank=True, db_column='id_administrador', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='id_docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='id_lista_chequeo',
            field=models.ForeignKey(db_column='id_lista_chequeo', on_delete=django.db.models.deletion.PROTECT, to='gen_infos.listachequeo'),
        ),
        migrations.AlterField(
            model_name='geninfo',
            name='tipo',
            field=models.CharField(choices=[('csv', '.csv'), ('pdf', '.pdf'), ('word', '.docx')], default='csv', max_length=4),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_administrador',
            field=models.ForeignKey(db_column='id_administrador', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_docente',
            field=models.ForeignKey(db_column='id_docente', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_estudiante',
            field=models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.PROTECT, to='usuarios.estudiante'),
        ),
        migrations.AlterField(
            model_name='listachequeo',
            name='id_falta',
            field=models.ForeignKey(db_column='id_falta', on_delete=django.db.models.deletion.PROTECT, to='faltas.falta'),
        ),
    ]
