# Generated by Django 5.2 on 2025-05-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('archivo', models.CharField(max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFalta',
            fields=[
                ('id_tipo_falta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_falta', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id_falta', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
                ('id_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
                ('id_justificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faltas.justificacion')),
                ('id_tipo_falta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faltas.tipofalta')),
            ],
        ),
    ]
