# Generated by Django 5.2 on 2025-05-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id_falta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_falta', models.CharField(max_length=1)),
                ('desc', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('archivo', models.CharField(max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
