# Generated by Django 5.2 on 2025-05-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0001_initial'),
        ('usuarios', '0002_remove_administrador_id_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='id_tipo_falta',
        ),
        migrations.AddField(
            model_name='falta',
            name='tipo_falta',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estudiante'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_justificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faltas.justificacion'),
        ),
        migrations.DeleteModel(
            name='TipoFalta',
        ),
    ]
