# Generated by Django 5.2 on 2025-05-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0002_initial'),
        ('usuarios', '0002_alter_administrador_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='id_administrador',
            field=models.ForeignKey(blank=True, db_column='id_administrador', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_estudiante',
            field=models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.PROTECT, to='usuarios.estudiante'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='id_justificacion',
            field=models.ForeignKey(blank=True, db_column='id_justificacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='faltas.justificacion'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='tipo_falta',
            field=models.CharField(choices=[('1', 'Leve'), ('2', 'Moderada'), ('3', 'Grave')], default='1', max_length=1),
        ),
    ]
